name: stox
description: "Sistema de Gestão de Inventário STOX - Agrobusiness"
version: 1.0.0+2

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0 
  path: ^1.9.0 
  connectivity_plus: ^6.1.5
  mobile_scanner: ^5.0.0 
  audioplayers: ^6.6.0
  vibration: ^3.1.8
  barcode_widget: ^2.0.4
  printing: ^5.11.0
  blue_thermal_printer: ^1.2.3
  permission_handler: ^12.0.1
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  csv: ^6.0.0
  image_picker: ^1.2.1
  google_mlkit_text_recognition: ^0.15.1
  image_cropper: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 
  # Plugins para automação de ícones e splash
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: "^2.4.0"

# Configuração do Ícone que vai para a Loja/Android (Usa o logo.png)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

# Configuração da Tela de Abertura (Splash)
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png           # Ícone de sistema
    - assets/images/Logo_colorida.png  # Logo das telas principais
    - assets/images/sap-logo.png
    - assets/sounds/error_beep.mp3
    - assets/sounds/beep.mp3
    - assets/sounds/fail.mp3
    - assets/sounds/check.mp3